import React, { Component } from 'react'

class TripsPage extends Component {
    render() {
        return (
            <div>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
                <p>Trips</p>
            </div>
        )
    }
}

export default TripsPage
